jobs:
  build:
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        key: samza-ci-gradle-cache
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
    strategy:
      matrix:
        java-version:
        - 8.0.232
    timeout-minutes: 60
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
